packages:
  - "packages/*"
  - "site"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  iso-constants: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260926.0-alpha
  - wrangler@4.142.0
