/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackageRouteImport } from './routes/_package'
import { Route as PackageNpmSplatRouteImport } from './routes/_package.npm.$'
import { Route as PackageSrcSplatRouteImport } from './routes/_package.src.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/_package',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageNpmSplatRoute = PackageNpmSplatRouteImport.update({
  id: '/npm/$',
  path: '/npm/$',
  getParentRoute: () => PackageRoute,
} as any)
const PackageSrcSplatRoute = PackageSrcSplatRouteImport.update({
  id: '/src/$',
  path: '/src/$',
  getParentRoute: () => PackageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/npm/$': typeof PackageNpmSplatRoute
  '/src/$': typeof PackageSrcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/npm/$': typeof PackageNpmSplatRoute
  '/src/$': typeof PackageSrcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_package': typeof PackageRouteWithChildren
  '/_package/npm/$': typeof PackageNpmSplatRoute
  '/_package/src/$': typeof PackageSrcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/npm/$' | '/src/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/npm/$' | '/src/$'
  id: '__root__' | '/' | '/_package' | '/_package/npm/$' | '/_package/src/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageRoute: typeof PackageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_package': {
      id: '/_package'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_package/npm/$': {
      id: '/_package/npm/$'
      path: '/npm/$'
      fullPath: '/npm/$'
      preLoaderRoute: typeof PackageNpmSplatRouteImport
      parentRoute: typeof PackageRoute
    }
    '/_package/src/$': {
      id: '/_package/src/$'
      path: '/src/$'
      fullPath: '/src/$'
      preLoaderRoute: typeof PackageSrcSplatRouteImport
      parentRoute: typeof PackageRoute
    }
  }
}

interface PackageRouteChildren {
  PackageNpmSplatRoute: typeof PackageNpmSplatRoute
  PackageSrcSplatRoute: typeof PackageSrcSplatRoute
}

const PackageRouteChildren: PackageRouteChildren = {
  PackageNpmSplatRoute: PackageNpmSplatRoute,
  PackageSrcSplatRoute: PackageSrcSplatRoute,
}

const PackageRouteWithChildren =
  PackageRoute._addFileChildren(PackageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageRoute: PackageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
